#
# Generated by erpcgen 1.9.0 on Wed Jun  1 03:45:17 2022.
#
# AUTOGENERATED - DO NOT EDIT
#

# Abstract base class for BBCarService
class IBBCarService(object):
    SERVICE_ID = 1
    INFO_ID = 1

    def info(self):
        raise NotImplementedError()


