#
# Generated by erpcgen 1.9.0 on Wed Jun  1 03:45:17 2022.
#
# AUTOGENERATED - DO NOT EDIT
#

import erpc
from . import common, interface

# Client for BBCarService
class BBCarServiceService(erpc.server.Service):
    def __init__(self, handler):
        super(BBCarServiceService, self).__init__(interface.IBBCarService.SERVICE_ID)
        self._handler = handler
        self._methods = {
                interface.IBBCarService.INFO_ID: self._handle_info,
            }

    def _handle_info(self, sequence, codec):
        # Read incoming parameters.

        # Invoke user implementation of remote function.
        self._handler.info()

        # Prepare codec for reply message.
        codec.reset()

        # Construct reply message.
        codec.start_write_message(erpc.codec.MessageInfo(
            type=erpc.codec.MessageType.kReplyMessage,
            service=interface.IBBCarService.SERVICE_ID,
            request=interface.IBBCarService.INFO_ID,
            sequence=sequence))


